-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 13:04:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS mydb
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE mydb;

<<<<<<< HEAD
CREATE TABLE Пользователи (
    id_пользователя INT AUTO_INCREMENT PRIMARY KEY,
    логин VARCHAR(50) UNIQUE NOT NULL,
    пароль_hash VARCHAR(255) NOT NULL,
    роль ENUM('admin','worker') DEFAULT 'worker',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
=======
>>>>>>> 3b4f349933548da8251d14636178f1a05d9906f0
-- Клиенты
CREATE TABLE Клиенты (
    id_клиента INT AUTO_INCREMENT PRIMARY KEY,
    фамилия VARCHAR(50) NOT NULL,
    имя VARCHAR(50) NOT NULL,
    отчество VARCHAR(50),
    телефон VARCHAR(20),
    дата_рождения DATE,
    email VARCHAR(100)
);

-- Абонементы
CREATE TABLE Абонементы (
    id_абонемента INT AUTO_INCREMENT PRIMARY KEY,
    тип VARCHAR(50) NOT NULL,
    срок_дней INT NOT NULL,
    цена DECIMAL(10,2) NOT NULL,
    количество_посещений INT
);

-- Тренировки
CREATE TABLE Тренировки (
    id_тренировки INT AUTO_INCREMENT PRIMARY KEY,
    название VARCHAR(100) NOT NULL,
    тренер VARCHAR(100),
    макс_участников INT
);

-- Покупка абонемента
CREATE TABLE Покупка_абонемента (
    id_покупки INT AUTO_INCREMENT PRIMARY KEY,
    дата_покупки DATE NOT NULL,
    дата_активации DATE,
    дата_окончания DATE,
    id_клиента INT NOT NULL,
    id_абонемента INT NOT NULL,

    CONSTRAINT fk_покупка_клиент
        FOREIGN KEY (id_клиента)
        REFERENCES Клиенты(id_клиента),

    CONSTRAINT fk_покупка_абонемент
        FOREIGN KEY (id_абонемента)
        REFERENCES Абонементы(id_абонемента)
);

-- Запись на тренировку
CREATE TABLE Запись_на_тренировку (
    id_записи INT AUTO_INCREMENT PRIMARY KEY,
    дата DATE NOT NULL,
    время TIME NOT NULL,
    статус VARCHAR(20),
    id_клиента INT NOT NULL,
    id_тренировки INT NOT NULL,

    CONSTRAINT fk_запись_клиент
        FOREIGN KEY (id_клиента)
        REFERENCES Клиенты(id_клиента),

    CONSTRAINT fk_запись_тренировка
        FOREIGN KEY (id_тренировки)
        REFERENCES Тренировки(id_тренировки)
);

-- Посещения
CREATE TABLE Посещения (
    id_посещения INT AUTO_INCREMENT PRIMARY KEY,
    дата DATE NOT NULL,
    время TIME NOT NULL,
    id_клиента INT NOT NULL,
    id_тренировки INT,

    CONSTRAINT fk_посещение_клиент
        FOREIGN KEY (id_клиента)
        REFERENCES Клиенты(id_клиента),

    CONSTRAINT fk_посещение_тренировка
        FOREIGN KEY (id_тренировки)
        REFERENCES Тренировки(id_тренировки)
);
