-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 14:34:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Клиенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Клиенты` (
  `ID_Клиента` INT NOT NULL AUTO_INCREMENT,
  `ФИО` VARCHAR(100) NOT NULL,
  `Телефон` VARCHAR(20) NOT NULL,
  `Дата_рождения` DATE NULL,
  PRIMARY KEY (`ID_Клиента`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Абонементы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Абонементы` (
  `ID_Абонемента` INT NOT NULL AUTO_INCREMENT,
  `Тип` VARCHAR(50) NOT NULL,
  `Срок` INT NOT NULL,
  `Цена` DECIMAL(10,2) NOT NULL,
  `Количество_посещений` INT NULL,
  PRIMARY KEY (`ID_Абонемента`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Покупка_абонемента`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Покупка_абонемента` (
  `ID_Покупки` INT NOT NULL AUTO_INCREMENT,
  `ID_Клиента` INT NOT NULL,
  `ID_Абонемента` INT NOT NULL,
  `Дата_покупки` DATE NOT NULL,
  `Дата_активации` DATE NULL,
  `Дата_окончания` DATE NULL,
  PRIMARY KEY (`ID_Покупки`),
  INDEX `fkclient_idx` (`ID_Клиента` ASC) VISIBLE,
  INDEX `fkab_idx` (`ID_Абонемента` ASC) VISIBLE,
  CONSTRAINT `fkclient`
    FOREIGN KEY (`ID_Клиента`)
    REFERENCES `mydb`.`Клиенты` (`ID_Клиента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkab`
    FOREIGN KEY (`ID_Абонемента`)
    REFERENCES `mydb`.`Абонементы` (`ID_Абонемента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Тренировки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Тренировки` (
  `ID_Тренировки` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(100) NOT NULL,
  `Тренер` VARCHAR(100) NOT NULL,
  `Макс_количество` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Тренировки`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Запись_на_тренировку`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Запись_на_тренировку` (
  `ID_Записи` INT NOT NULL AUTO_INCREMENT,
  `ID_Клиента` INT NOT NULL,
  `ID_Тренировки` INT NOT NULL,
  `Время` TIME NOT NULL,
  `Статус` VARCHAR(30) NULL,
  `Дата` DATE NOT NULL,
  PRIMARY KEY (`ID_Записи`),
  INDEX `fktren_idx` (`ID_Тренировки` ASC) VISIBLE,
  INDEX `fkclnt_idx` (`ID_Клиента` ASC) VISIBLE,
  CONSTRAINT `fktren`
    FOREIGN KEY (`ID_Тренировки`)
    REFERENCES `mydb`.`Тренировки` (`ID_Тренировки`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkclnt`
    FOREIGN KEY (`ID_Клиента`)
    REFERENCES `mydb`.`Клиенты` (`ID_Клиента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Посещения`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Посещения` (
  `ID_Посещения` INT NOT NULL AUTO_INCREMENT,
  `ID_Клиента` INT NOT NULL,
  `ID_Покупки` INT NOT NULL,
  `Дата` DATE NOT NULL,
  `Время` TIME NOT NULL,
  PRIMARY KEY (`ID_Посещения`),
  INDEX `clientfk_idx` (`ID_Клиента` ASC) VISIBLE,
  INDEX `fkpok_idx` (`ID_Покупки` ASC) VISIBLE,
  CONSTRAINT `clientfk`
    FOREIGN KEY (`ID_Клиента`)
    REFERENCES `mydb`.`Клиенты` (`ID_Клиента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkpok`
    FOREIGN KEY (`ID_Покупки`)
    REFERENCES `mydb`.`Покупка_абонемента` (`ID_Покупки`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
